### ISSUE TITLE
custom_lua_shared_dict to add in nginx conf for crowdsec plugin

### ISSUE THREAD

**Issue by he2ss** [mostafahussein/crowdsec-bouncer-apisix-demo#2]
this config is missing in the blog post and the demo files to allow crowdsec storing in the lua_shared_dict. By adding this config it solves the issue:

```
nginx_config:
    custom_lua_shared_dict:
      plugin-crowdsec-bouncer: 50m
```

**Comment by mostafahussein** [comment]
Yes, I had it locally, seems I missed it during the review 😄

**Comment by he2ss** [comment]
My bad, it's already in your article.
